<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Sign_In</name>
   <tag></tag>
   <elementGuidId>465d24c4-5c89-483e-86bd-270b0ae9cfd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.v-btn.v-btn--block.v-btn--flat.v-theme--light.bg-primary.v-btn--density-default.rounded-lg.v-btn--size-default.v-btn--variant-elevated.text-capitalize.font-weight-bold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c028285f-4968-4ce4-9a53-e40f1dd42761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>84de621c-c159-4339-8dfe-608a845ed482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-btn v-btn--block v-btn--flat v-theme--light bg-primary v-btn--density-default rounded-lg v-btn--size-default v-btn--variant-elevated text-capitalize font-weight-bold</value>
      <webElementGuid>8f8a06d6-6258-4b03-97b6-8f882b88b8cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sign In </value>
      <webElementGuid>5dbee12f-7cb9-401e-a62e-04d0113e0afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__nuxt&quot;)/div[@class=&quot;d-flex flex-column align-center justify-center&quot;]/div[1]/div[@class=&quot;v-card v-card--flat v-theme--light v-card--density-default rounded-xl v-card--variant-elevated&quot;]/div[@class=&quot;v-card-text px-7 py-5&quot;]/form[@class=&quot;v-form&quot;]/div[@class=&quot;v-row&quot;]/div[@class=&quot;v-col v-col-12&quot;]/button[@class=&quot;v-btn v-btn--block v-btn--flat v-theme--light bg-primary v-btn--density-default rounded-lg v-btn--size-default v-btn--variant-elevated text-capitalize font-weight-bold&quot;]</value>
      <webElementGuid>12893918-a5bd-4233-b2a4-2cb0ecf9b44d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>51988128-bc52-4a06-bca4-b2d84666fae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div/div/div/div[2]/form/div/div[4]/button</value>
      <webElementGuid>8e54436c-58a0-4b96-b279-46bed9018db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/following::button[1]</value>
      <webElementGuid>44c4cde5-b912-449f-a40c-cbd2fd646322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password is required'])[1]/following::button[2]</value>
      <webElementGuid>3e293466-3a63-480c-af7b-4390cb426851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>f2fdca11-2da2-44f6-82de-13476c5e8629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Sign In ' or . = ' Sign In ')]</value>
      <webElementGuid>b2349f12-b489-4227-a148-6495043f6600</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
