<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form__email</name>
   <tag></tag>
   <elementGuidId>96b245ff-5bf6-4e68-9a5b-ea88510ceb6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8fb55c68-d508-49fa-b023-7727d164ebc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your email address</value>
      <webElementGuid>90e44ec8-8303-4402-aab1-293e1f5960d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1e254a68-0018-44e6-8c16-0aa4728ee99d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a305f872-7a4f-42b8-aa81-71ffea6c611c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-0</value>
      <webElementGuid>a7292cfb-2bca-4c9d-9e3d-db611b129a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>input-0-messages</value>
      <webElementGuid>b4957c47-0f71-4a11-a9f4-6328417ed89a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-field__input</value>
      <webElementGuid>a354c923-37ec-4798-8301-da102f6fd225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-0&quot;)</value>
      <webElementGuid>e01e3512-cf64-4497-9229-ea0db5a678c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-0']</value>
      <webElementGuid>b45dc534-3200-4572-8dbd-055d113987b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__nuxt']/div/div/div/div[2]/form/div/div/div/div[2]/div/div/div[3]/input</value>
      <webElementGuid>ca4ba3f3-109f-4810-abb2-bf5d604b4440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2fc0b1aa-f25a-47e8-a881-fd922f353318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter your email address' and @type = 'text' and @id = 'input-0']</value>
      <webElementGuid>de12c490-a98a-443d-b649-29fa180a51b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
