<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_password_is_required</name>
   <tag></tag>
   <elementGuidId>a49e2d8b-c7d9-4907-b8eb-fedf5dc870ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-2-messages > div.v-messages__message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='input-2-messages']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a60a56f8-c0c5-4003-b5ad-aa45adcc8dc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-messages__message</value>
      <webElementGuid>bc1148d1-13d7-430c-9f67-85264cd4b6bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password is required</value>
      <webElementGuid>6fed45f7-ac0c-435b-a8b8-c18f80eea876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-2-messages&quot;)/div[@class=&quot;v-messages__message&quot;]</value>
      <webElementGuid>e100b29c-a13e-435d-8094-976004607019</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='input-2-messages']/div</value>
      <webElementGuid>9a5e6735-d126-4362-9bf4-47f05a54727b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::div[19]</value>
      <webElementGuid>02c4bf81-fae8-463d-b5fc-0a6c157dab47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/preceding::div[1]</value>
      <webElementGuid>9574cb53-0e7c-4787-b842-0da413afc874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[1]/preceding::div[2]</value>
      <webElementGuid>e04a7528-2bc4-49ff-8ff7-e69afc07aab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Password is required']/parent::*</value>
      <webElementGuid>56b51620-6664-43da-b738-9ad84e68ef1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/div/div</value>
      <webElementGuid>b2136260-9b7a-4df0-ba84-43c9e29d8447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Password is required' or . = 'Password is required')]</value>
      <webElementGuid>13da40e9-4479-45ca-a2be-ac258439a1fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
