<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_email_is_required</name>
   <tag></tag>
   <elementGuidId>8100c5f5-823c-493f-adaa-c1d26b518f18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.v-messages__message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='input-0-messages']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bbf1115d-09bb-46d5-a2a3-c7474da60bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-messages__message</value>
      <webElementGuid>7b553d5e-be79-4f1a-9461-a1d129b1ba3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email is required</value>
      <webElementGuid>b708534f-be8b-4ea8-89a1-10ac19a0a351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-0-messages&quot;)/div[@class=&quot;v-messages__message&quot;]</value>
      <webElementGuid>515bee68-5a67-40a1-9a95-f7de08fa08f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='input-0-messages']/div</value>
      <webElementGuid>8784af95-895b-4c0a-a8d2-7b674f71e204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[18]</value>
      <webElementGuid>7605aa09-ecfe-4a07-99ea-4f80e3445e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::div[1]</value>
      <webElementGuid>14074367-2d73-4b40-904b-193a1d541400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Email is required']/parent::*</value>
      <webElementGuid>bf5667c3-1db0-4ea8-b96e-29cd44bdd22d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div</value>
      <webElementGuid>00c20d32-8b4c-4fb0-a1a9-95ab25a0e284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Email is required' or . = 'Email is required')]</value>
      <webElementGuid>e9de5e4a-d960-4102-bfe5-6747c05b856f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
